### ISSUE TITLE
powerline fail to install

### ISSUE THREAD

**Issue by Nicodonald** [shawncplus/dotfiles#3]
Everytime I try to install the dotfiles (I only use the vim ones) powerline fail to install.
I tried the steps manually and the pip install step fail with : 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 277, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '/home/support/.local/bin')

**Comment by moraya-re** [comment]
You can use https://github.com/bling/vim-airline. It works same as powerline and is written in vimscript.
Give it a try.

**Comment by shawncplus** [comment]
Not at a shell at the moment so I can't try this out but you could give a shot at replacing the `pip` calls with `pip-2.6` to see if that works. I don't believe I use 2.7 on any of my installs so something I've never run into

**Comment by Nicodonald** [comment]
I've installed the dotfiles successfully recently, don't know what changed (a few yum updates since the ticket was openned) so I'm closing.
